<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Trip Fuel Cost Estimator</title>
    <?php echo $this->headLink()->appendStylesheet('/css/global.css') ?>
    <?php echo $this->headScript()->appendFile('/js/jquery-1.4.3.min.js') ?>
</head>
<body>
<div id="header" style="background-color: #EEEEEE; height: 30px;">
    <div id="header-logo" style="float: left">
        <b>Trip Fuel Cost Estimator</b>
    </div>
</div>

<?php echo $this->layout()->content ?>

</body>
</html>
